AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Ticket Backend

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30

Resources:

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Tickets
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S

      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH

  TicketQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TicketQueue

  AttachmentsBucket:
    Type: AWS::S3::Bucket

  HelloWorldFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler

      Policies:
        - DynamoDBCrudPolicy:
            TableName: Tickets

      Events:
        TicketAPI:
          Type: Api

          Properties:
            Path: /tickets
            Method: get

Outputs:

  ApiEndpoint:
    Description: API Endpoint

    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/tickets

  DynamoDBTable:
    Value: !Ref TicketsTable

  QueueName:
    Value: !Ref TicketQueue

  BucketName:
    Value: !Ref AttachmentsBucket